[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-lib = { path = "../../crates/agent-lib" }

anyhow = { workspace = true }
futures = { workspace = true }
structopt = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true }
