[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

# [features]
# aws = ["aws-config"]

[dependencies]
agent-lib = { path = "../../crates/agent-lib" }

libc = { workspace = true }

apt-cmd = { workspace = true }
async-process = { workspace = true }
anyhow ={ workspace = true } 
structopt = { workspace = true }
sudo = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
rustls-pemfile = { workspace=true }
